const POKEMON_FORM_LABELS: Record<string, readonly string[]> = {
  Aegislash: ["Blade"],
  Alcremie: [
    "Ruby Cream",
    "Matcha Cream",
    "Mint Cream",
    "Lemon Cream",
    "Salted Cream",
    "Ruby Swirl",
    "Caramel Swirl",
    "Rainbow Swirl",
    "Gmax",
  ],
  Arceus: ["Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Fire", "Water", "Grass", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"],
  Articuno: ["Galar"],
  Avalugg: ["Hisui"],
  Basculin: ["Blue-Striped", "White-Striped"],
  Braviary: ["Hisui"],
  Calyrex: ["Ice", "Shadow"],
  Castform: ["Sunny", "Rainy", "Snowy"],
  Cramorant: ["Gulping", "Gorging"],
  Darmanitan: ["Zen", "Galar", "Galar-Zen"],
  Darumaka: ["Galar"],
  Decidueye: ["Hisui"],
  Deoxys: ["Attack", "Defense", "Speed"],
  Dialga: ["Origin"],
  Diglett: ["Alola"],
  Dugtrio: ["Alola"],
  Eiscue: ["Noice"],
  Electrode: ["Hisui"],
  Enamorus: ["Therian"],
  Eternatus: ["Eternamax"],
  Exeggutor: ["Alola"],
  Farfetchd: ["Galar"],
  "Farfetch'd": ["Galar"],
  Flabebe: ["Yellow", "Orange", "Blue", "White"],
  Floette: ["Yellow", "Orange", "Blue", "White", "Eternal"],
  Florges: ["Yellow", "Orange", "Blue", "White"],
  Furfrou: ["Heart", "Star", "Diamond", "Debutante", "Matron", "Dandy", "La Reine", "Kabuki", "Pharaoh"],
  Gastrodon: ["East"],
  Genesect: ["Douse", "Chill", "Burn", "Shock"],
  Geodude: ["Alola"],
  Giratina: ["Origin"],
  Golem: ["Alola"],
  Goodra: ["Hisui"],
  Graveler: ["Alola"],
  Greninja: ["Ash"],
  Grimer: ["Alola"],
  Groudon: ["Primal"],
  Growlithe: ["Hisui"],
  Hoopa: ["Unbound"],
  Indeedee: ["F"],
  Keldeo: ["Resolute"],
  Kyogre: ["Primal"],
  Kyurem: ["White", "Black"],
  Landorus: ["Therian"],
  Lilligant: ["Hisui"],
  Linoone: ["Galar"],
  Lucario: ["Mega"],
  Lycanroc: ["Midnight", "Dusk"],
  Magearna: ["Original"],
  Marowak: ["Alola"],
  Meloetta: ["Pirouette"],
  Meowth: ["Alola", "Galar"],
  "Mr. Mime": ["Galar"],
  Mimikyu: ["Busted", "Totem", "Busted-Totem"],
  Minior: ["Meteor", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet"],
  Moltres: ["Galar"],
  Morpeko: ["Hangry"],
  Muk: ["Alola"],
  Necrozma: ["Dusk-Mane", "Dawn-Wings", "Ultra"],
  Ninetales: ["Alola"],
  Ogerpon: ["Wellspring", "Hearthflame", "Cornerstone", "Wellspring-Tera", "Hearthflame-Tera", "Cornerstone-Tera", "Teal-Tera"],
  Oricorio: ["Pom-Pom", "Pa'u", "Sensu"],
  Palafin: ["Hero"],
  Palkia: ["Origin"],
  Persian: ["Alola"],
  Pikachu: ["Original-Cap", "Hoenn-Cap", "Sinnoh-Cap", "Unova-Cap", "Kalos-Cap", "Alola-Cap", "Partner-Cap", "World-Cap", "Gmax"],
  Ponyta: ["Galar"],
  Pumpkaboo: ["Small", "Large", "Super"],
  Qwilfish: ["Hisui"],
  Raichu: ["Alola"],
  Rapidash: ["Galar"],
  Raticate: ["Alola", "Alola-Totem"],
  Rattata: ["Alola"],
  Rayquaza: ["Mega"],
  Rotom: ["Heat", "Wash", "Frost", "Fan", "Mow"],
  Samurott: ["Hisui"],
  Sandshrew: ["Alola"],
  Sandslash: ["Alola"],
  Sawsbuck: ["Summer", "Autumn", "Winter"],
  Shaymin: ["Sky"],
  Shellos: ["East"],
  Sliggoo: ["Hisui"],
  Slowbro: ["Galar", "Mega"],
  Slowking: ["Galar"],
  Slowpoke: ["Galar"],
  Sneasel: ["Hisui"],
  Squawkabilly: ["Blue", "Yellow", "White"],
  Stunfisk: ["Galar"],
  Tatsugiri: ["Droopy", "Stretchy"],
  Tauros: ["Paldea-Combat", "Paldea-Blaze", "Paldea-Aqua"],
  Terapagos: ["Terastal", "Stellar"],
  Thundurus: ["Therian"],
  Tornadus: ["Therian"],
  Toxtricity: ["Low-Key", "Gmax"],
  Typhlosion: ["Hisui"],
  Urshifu: ["Rapid-Strike", "Gmax", "Rapid-Strike-Gmax"],
  Vivillon: [
    "Archipelago",
    "Continental",
    "Elegant",
    "Garden",
    "High-Plains",
    "Icy-Snow",
    "Jungle",
    "Marine",
    "Modern",
    "Monsoon",
    "Ocean",
    "Polar",
    "River",
    "Sandstorm",
    "Savanna",
    "Sun",
    "Tundra",
    "Fancy",
    "Poke-Ball",
  ],
  Voltorb: ["Hisui"],
  Vulpix: ["Alola"],
  Weezing: ["Galar"],
  Wishiwashi: ["School"],
  Wooper: ["Paldea"],
  Wormadam: ["Sandy", "Trash"],
  Xerneas: ["Active"],
  Yamask: ["Galar"],
  Zapdos: ["Galar"],
  Zacian: ["Crowned"],
  Zamazenta: ["Crowned"],
  Zigzagoon: ["Galar"],
  Zoroark: ["Hisui"],
  Zorua: ["Hisui"],
  Zygarde: ["10", "Complete"],
};

const NORMALIZED_FORM_LABELS = new Map(Object.entries(POKEMON_FORM_LABELS).map(([species, labels]) => [normalizeSpeciesName(species), labels]));

export function pokemonFormSuffix(baseSpeciesName: string, formIndex: number): string | undefined {
  if (!Number.isInteger(formIndex) || formIndex <= 0) return undefined;
  return NORMALIZED_FORM_LABELS.get(normalizeSpeciesName(baseSpeciesName))?.[formIndex - 1];
}

export function pokemonFormLabel(baseSpeciesName: string, formIndex: number): string {
  return pokemonFormSuffix(baseSpeciesName, formIndex) ?? `Form ${formIndex}`;
}

export function pokemonFormSpeciesLabel(baseSpeciesName: string, formIndex: number): string {
  const suffix = pokemonFormSuffix(baseSpeciesName, formIndex);
  return suffix ? `${baseSpeciesName}-${suffix}` : `${baseSpeciesName} Form ${formIndex}`;
}

function normalizeSpeciesName(value: string): string {
  return value
    .normalize("NFKD")
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "");
}
