"""Measure packaged follower buffers and document the implemented memory reduction.

Reads artifacts only; does not modify runtime code, ROMs, or saves.
"""
import argparse, json, struct
from pathlib import Path
from collections import Counter
import ndspy.rom
from verify_packaged import read_module, ELFFile
HERE=Path(__file__).resolve().parent
APP=HERE.parents[1]

def audit(profile,rom_path):
 assets=APP/'src/assets/following';build=HERE/'build'
 if profile=='white2upgrade':assets/='white2upgrade';build/='white2upgrade'
 if profile=='black2':assets/='black2';build/='black2'
 if profile=='white2italy':assets/='white2italy';build/='white2italy'
 manifest=json.loads((assets/'runtime.json').read_text());modules=[];objects=[]
 for name in ['Core','Events','Field']:
  stem='PokewebFollowing'+name+('B2' if profile=='black2' else 'W2I' if profile=='white2italy' else 'W2');path=assets/(stem+'.dll');raw=path.read_bytes()
  code,bss,symbols,rels=read_module(path)
  modules.append(dict(name=stem,fileBytes=len(raw),codeAndInitializedData=len(code),bss=bss,
                      codePlusBss=len(code)+bss,expandedModuleBytes=struct.unpack_from('<I',raw,4)[0],
                      symbols=len(symbols),exportedSymbols=sum(bool(s[4]&1) for s in symbols),
                      allSymbolNamesStripped=all(s[0]==0 for s in symbols)))
  if name=='Field':
   assert (build/(stem+'.dll')).read_bytes()==raw,'ELF/build no longer matches packaged DLL'
   with (build/(stem+'.elf')).open('rb') as stream:
    elf=ELFFile(stream)
    for s in elf.get_section_by_name('.symtab').iter_symbols():
     if s['st_info']['type']=='STT_OBJECT' and s['st_size']:
      objects.append(dict(name=s.name,bytes=s['st_size'],section=elf.get_section(s['st_shndx']).name))
 rom=ndspy.rom.NintendoDSRom.fromFile(rom_path)
 data=rom.getFileByName('following/runtime-registry.bin');version=struct.unpack_from('<H',data,4)[0]
 count=struct.unpack_from('<H',data,12)[0];species=Counter()
 for i in range(count):
  value=struct.unpack_from('<I' if version in (2,4) else '<H',data,32+i*(12 if version in (2,4) else 24))[0]
  species[value>>11 if version in (2,4) else value]+=1
 sizes={o['name']:o['bytes'] for o in objects}
 assert sizes['fwfield_page']==1024 and sizes['dataBytes']==8192 and sizes['contextBytes']==4096
 assert sizes['fwfield_follower']==1852
 assert sizes['fwfield_index']==(1025 if profile=='white2upgrade' else 651)*2
 allocatedRegistry=0
 total=sum(m['codePlusBss'] for m in modules)+allocatedRegistry
 return dict(profile=profile,version=manifest['version'],modules=modules,
             largestObjects=sorted(objects,key=lambda o:o['bytes'],reverse=True)[:15],
             fixedPayloadBytes=total,registryBytes=len(data),registryRecords=count,
             registryHeapBytes=allocatedRegistry,pageBytes=sizes['fwfield_page'],indexBytes=sizes['fwfield_index'],
             conversationCapacity=sizes['dataBytes'],contextualCapacity=sizes['contextBytes'],giftScratchCapacity=sizes['contextBytes'],
             largestSpeciesGroups=species.most_common(5),maxSpeciesBytesAtRuntimeStride=max(species.values())*(12 if version in (2,4) else 24),
             directoryBytesAt16BitRowOffsets=(max(species)+2)*2,
             conversationBytes=len(rom.getFileByName('following/interactions.bin')),contextualBytes=len(rom.getFileByName('following/contextual-dialogues.narc')),giftBytes=len(rom.getFileByName('following/contextual-items.narc')))

def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('stock_rom',type=Path);p.add_argument('black2_rom',type=Path);p.add_argument('upgrade_rom',type=Path);a=p.parse_args()
 reports=[audit('stock',a.stock_rom),audit('black2',a.black2_rom),audit('white2upgrade',a.upgrade_rom)]
 previous=[dict(profile='stock',version='0.6.31-alpha',fixedPayloadBytes=46648),dict(profile='black2',version='0.6.31-alpha',fixedPayloadBytes=46648),dict(profile='white2upgrade',version='0.7.22-alpha',fixedPayloadBytes=47628)]
 out={'measurements':reports,'previousReleaseMeasurements':previous,
      'limits':'Fixed payloads exclude loader metadata, allocator overhead, native graphics/UI allocations, stack usage and VRAM. Expanded module sizes are loader image requirements, not measured steady-state heap charges.',
      'implementationStatus':'ROM registry streaming and 8 KiB conversation buffers implemented; automated checks passed, game emulator acceptance pending.'}
 (HERE/'MEMORY-AUDIT.json').write_text(json.dumps(out,indent=2)+'\n')
 lines=['# Follower memory footprint','', 'Generated by `audit_memory.py` from the packaged DLLs, matching debug ELFs and delivered ROM data.', '',
        '| Profile | Previous fixed payload | New fixed payload | Species index / page cache | Generic capacity / data | Context capacity / data | Gift scratch / data |', '|---|---:|---:|---:|---:|---:|---:|']
 for r,old in zip(reports,previous):
  lines.append(f"| {r['profile']} {r['version']} | {old['fixedPayloadBytes']:,} B | {r['fixedPayloadBytes']:,} B | {r['indexBytes']:,} / {r['pageBytes']:,} B | {r['conversationCapacity']:,} / {r['conversationBytes']:,} B | {r['contextualCapacity']:,} / {r['contextualBytes']:,} B | {r['giftScratchCapacity']:,} / {r['giftBytes']:,} B |")
 lines+=['',
  'The fixed payload is packaged code plus initialized data and BSS, including',
  'the index, cache and conversation buffer. Neither new nor preceding release',
  'allocates a separate registry. Loader bookkeeping, allocator overhead,',
  'stack, native actor/effect/message allocations and VRAM remain separate.',
  'These numbers are not whole-game peak heap measurements.', '',
  'The 64-record trail replaces the earlier 256-record trail. Each 28-byte record stores',
  'a sampled world position and route metadata. The follower sidecar shrinks from',
  '7,228 to 1,852 bytes, saving 5,376 bytes in the field module for every profile.',
  'A full trail still recalls and reseeds safely; slow movement and complex paths',
  'require human emulator acceptance to confirm the smaller bound is sufficient.', '',
  '## Implemented behavior','',
  '- The complete appearance registry stays in ROM: 61,808 bytes for stock and',
  '  56,648 bytes for Upgrade. No full-registry buffer or heap allocation remains.',
  '- Initialization streams validation and both checksums through a 1 KiB cache,',
  '  builds 16-bit species row boundaries, then publishes resident lookup bounds.',
  '- Selection reads only the relevant species pages. Unown in the stock 24-byte',
  '  format spans pages; lookup scoring remains identical across boundaries.',
  '  Cache hits do not read the file. Movement and drawing perform no registry I/O.',
  '- Invalid, short or missing data suppresses following safely. Every opened',
  '  file is closed. Unload clears cached state and the resident extension bounds.',
  '- The resident bridge is ABI 2. Its reader callback is synchronous and is',
  '  never retained after initialization. Core/field updates are staged together.',
  '- Generic conversation capacity is 8,192 bytes. Build, installation and runtime reject',
  '  oversized data rather than truncating it; current messages use 3,852 bytes.',
  '- Contextual dialogue and one-time gifts share one 4,096-byte fixed NARC scratch buffer; gifts load first and dialogue replaces it only when no unclaimed gift matches. It is loaded only',
  '  when the first follower conversation is attempted, with no PMC shared-heap allocation.',
  '- Upgrade reaction selection now accepts species 1–1023; stock remains 1–649.',
  '  Egg IDs remain excluded. Actual selected species reaches the native cry',
  '  call; this change does not install additional cry assets.', '',
  'All three builds still use `-Os` and RPM `--strip`. Packaged symbol names are',
  'stripped; exports/import hashes and required relocations remain. Debug ELFs',
  'are not installed into ROM. History capacity and drawing corrections are unchanged; trail distance now accounts for sprite width.', '',
  '## Verification and limits','',
  'Stock and Upgrade packaged CPU tests compare every installed appearance and fallback,',
  'exercise 100 load/cache/unload cycles per profile, inject 16 file/data failures,',
  'and check all 65,536 object codes with zero registry allocations. Black 2',
  'passed its exact-ROM contract and packaged branch checks. Native FS seek',
  'instructions execute against a mocked synchronous filesystem dispatcher.',
  'An earlier isolated regression using the supplied Upgrade state retained 100,332 bytes',
  'free on application heap 1 before, during and after registry setup. This',
  'does not measure native rendering allocations or PMC loader peaks.',
  'Host reaction tests cover both species limits and exact 8 KiB data boundaries.',
  'The Upgrade 100-conversation CPU test includes species 650, 722, 810 and 1023.',
  'See VALIDATION.md for installer/build evidence and the human checklists for',
  'cold boot, PC changes, conversations, forms and repeated transitions.',
  'No game emulator or hardware was run for these releases.', '']
 (HERE/'MEMORY-AUDIT.md').write_text('\n'.join(lines))
 print(json.dumps(out,indent=2))
if __name__=='__main__':main()
