"""Generate the runtime allowlist from the reviewed, pinned command policy."""
import json
from pathlib import Path
HERE=Path(__file__).resolve().parent
def generate():
 policy=json.loads((HERE/'event-policy.json').read_text())
 commands=[entry['opcode'] for entry in policy['commands']]
 if policy['abi']!=1 or commands!=sorted(set(commands)) or any(not 0<=n<0x2f3 for n in commands):
  raise ValueError('Invalid event command policy')
 for entry in policy['commands']:
  if not entry['handler']&1 or len(bytes.fromhex(entry['expectedHex']))<4:
   raise ValueError('Allowlisted command requires a pinned non-null Thumb handler')
 finishers=policy['finishers']
 indices=[entry['index'] for entry in finishers]
 if indices!=sorted(set(indices)) or any(not 0<=n<14 for n in indices):
  raise ValueError('Invalid cleanup finisher policy')
 if any(not e['handler']&1 or len(bytes.fromhex(e['expectedHex']))<4 for e in finishers):
  raise ValueError('Cleanup finisher requires a pinned Thumb handler')
 lines=['/* Generated by generate_scene_policy.py; edit event-policy.json. */',
        f'#define FWS_SAFE_FINISHERS 0x{sum(1<<i for i in indices):08x}u',
        'static const uint16_t fws_safe_commands[]={']
 lines += [' '+','.join(f'0x{n:04x}' for n in commands[i:i+12])+',' for i in range(0,len(commands),12)]
 (HERE/'scene-policy.h').write_text('\n'.join(lines+['};','']))
if __name__=='__main__':generate()
