"""Render the complete non-allowlisted opcode register from the reviewed CSV."""

import argparse
import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "script-command-review.csv"
OUTPUT = HERE / "NON-ALLOWLISTED-COMMANDS.md"
GROUPS = (
    ("defer-actor-motion", "Actor motion and ownership"),
    ("defer-battle", "Battle and trade transitions"),
    ("defer-child-application", "Child applications"),
    ("defer-child-event", "Asynchronous child events"),
    ("defer-field-lifecycle", "Field and map lifecycle"),
    ("defer-party-mutation", "Party and Pokémon changes"),
    ("defer-presentation", "Presentation and cutscenes"),
    ("review-needed", "Unknown placeholder commands"),
    ("blank-name-in-sheet", "Unnamed command"),
    ("unused-null-slot", "Unused dispatch slots"),
    ("scoped-only", "Script-scoped exception"),
)


def render() -> str:
    with SOURCE.open(newline="") as source:
        rows = list(csv.DictReader(source))
    assert len(rows) == 0x2F3
    assert all(int(row["opcode"], 16) == index for index, row in enumerate(rows))
    remaining = [row for row in rows if not row["decision"].startswith("allow-")]
    lines = [
        "# Script commands outside the global follower allowlist",
        "",
        "Generated by `generate_unallowed_commands.py` from the opcode review CSV.",
        "Run it with `--check` to verify this document is current.",
        "",
        f"This is the complete set of **{len(remaining)}** stock US White 2 standard opcode slots",
        "outside the global allowlist. The matching [review](SCRIPT-COMMAND-REVIEW.md)",
        "explains the policy; [script-command-review.csv](script-command-review.csv)",
        "is the machine-readable source for this document. A command marked as a",
        "known risk is not necessarily unsafe in every script. It is excluded",
        "because retaining the follower through every use is not established.",
        "Unknown entries need behavior analysis; unused slots have no handler.",
        "The script-scoped exception is not globally allowed.",
        "",
    ]
    for decision, title in GROUPS:
        group = [row for row in remaining if row["decision"] == decision]
        if not group:
            continue
        classification = ("Known scene risk" if decision.startswith("defer-") else
                          "Unknown behavior" if decision in ("review-needed", "blank-name-in-sheet") else
                          "Unavailable" if decision == "unused-null-slot" else "Scoped only")
        lines.extend((f"## {title} ({len(group)}; {classification})", "",
                      "| Opcode | Sheet name | Reason for exclusion |",
                      "| --- | --- | --- |"))
        for row in group:
            name = row["name"] or "—"
            reason = row["reason"].replace("|", "\\|")
            lines.append(f"| `{row['opcode']}` | {name} | {reason} |")
        lines.append("")
    assert sum(len([row for row in remaining if row["decision"] == decision])
               for decision, _ in GROUPS) == len(remaining)
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the document is stale")
    args = parser.parse_args()
    wanted = render()
    if args.check:
        if OUTPUT.read_text() != wanted:
            raise SystemExit(f"Stale command register: {OUTPUT}")
    else:
        OUTPUT.write_text(wanted)
