"""Extract the verified HGSS ball/flash resources without changing the input ROM."""
import argparse,hashlib,json,struct,zlib
from pathlib import Path
import ndspy.rom,ndspy.narc
HERE=Path(__file__).resolve().parent
p=argparse.ArgumentParser(description=__doc__);p.add_argument('rom',type=Path);args=p.parse_args()
r=ndspy.rom.NintendoDSRom.fromFile(args.rom)
if bytes(r.idCode)!=b'IPKE':raise ValueError('Expected the inspected US HeartGold resource layout')
a=ndspy.narc.NARC(r.getFileByName('a/1/0/3'))
spec=[(129,b'BMD0',b'monstarball'),(104,b'BMD0',b'mb_out'),(164,b'BTA0',b'mb_out')]
files=[];entries=[]
for index,magic,name in spec:
 data=bytes(a.files[index])
 if data[:4]!=magic or name not in data:raise ValueError('Unexpected HGSS effect resource')
 files.append(data);entries.append({'member':index,'magic':magic.decode(),'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data)})
out=ndspy.narc.NARC();out.files=files;data=bytes(out.save())
# Match Pokeweb's canonical nameless FNT so export does not change the CRC.
fat_end=16+struct.unpack_from('<I',data,20)[0]
fnt_end=fat_end+struct.unpack_from('<I',data,fat_end+4)[0]
data=bytearray(data[:fat_end]+b'BTNF'+struct.pack('<I',16)+bytes.fromhex('0400000000000100')+data[fnt_end:])
struct.pack_into('<I',data,8,len(data));data=bytes(data)
assets=HERE.parents[1]/'src/assets/following'
(assets/'hgss-effects.narc').write_bytes(data)
(assets/'effects.json').write_text(json.dumps({'schemaVersion':1,'sourceGame':'HeartGold IPKE','archive':'a/1/0/3','members':entries,'sha256':hashlib.sha256(data).hexdigest(),'crc32':zlib.crc32(data),'bytes':len(data),'sendOutBallTicks':2,'flashTicks':8,'recallTintTicks':3,'recallShrinkTicks':5,'recallBallTicks':4},indent=2)+'\n')
(HERE/'effects_assets.h').write_text(f'/* Generated by import_effects.py; original compiled HGSS resources. */\n#define FW_EFFECT_BYTES {len(data)}u\n#define FW_EFFECT_CRC 0x{zlib.crc32(data):08x}u\n')
print('Imported HGSS ball, flash model and texture animation:',len(data),'bytes')
