import type { NARC } from "../nds/narc";
import type { ProjectState } from "../pokeweb/projectStore";
import { actionFor, actions, colors, newButton, type Button, type Document } from "../cgearButtons/document";
import { compile, preview, fingerprint, type Assets } from "../cgearButtons/compiler";
import { EditorHistory } from "../cgearButtons/editorState";
import { ensureCGearButtons, hasUnappliedButtons, resolveButtonAssets } from "../pokeweb/cgearButtonsModel";
import { getCGearQuickActionsStatus, installCGearQuickActions, disableCGearQuickActions, removeCGearQuickActions } from "../pokeweb/cgearQuickActionsModel";
import { escapeHtml as esc } from "./dom";
import { defaultSkins, encodeSkin, skinBytes, MAX_SKINS } from "../cgearButtons/skins";
import { nativePreview } from "../cgearButtons/nativePreview";
let generation=0;
export function stopCGearButtonsEditor(){generation++;}
export async function renderCGearButtonsEditor(project:ProjectState,root:HTMLElement,onDirty:()=>void){
  const run=++generation;root.innerHTML='<div class="cgear-editor"><h1>C-Gear Buttons</h1><p>Loading native graphics…</p></div>';
  let assets:Assets,baseBytes:Uint8Array;try{const resolved=await resolveButtonAssets(project);assets=resolved.assets;baseBytes=resolved.bytes;}catch(e){root.innerHTML=`<h1>C-Gear Buttons</h1><p>${esc((e as Error).message)}</p>`;return;}if(run!==generation)return;
  const state=ensureCGearButtons(project),history=new EditorHistory(state.document);let selected=state.document.buttons[0]?.id,zoom=3,snap=false,pose=0,design=0,theme=0,gender=0,busy=false,message="",lastArchive:Uint8Array|undefined,lastNativeGraphics:NARC|undefined,lastIndices=new Map<number,number>(),power=true,previewSkin=state.document.skins?.defaultId??0;
  const backgroundCache=new Map<string,ReturnType<typeof nativePreview>>();
  const doc=()=>history.document;
  function update(next:Document,before=doc()){if(history.commit(next,before)){state.document=history.document;onDirty();}render();}
  function edit(fn:(b:Button)=>void){const next=structuredClone(doc()),b=next.buttons.find(b=>b.id===selected);if(b){fn(b);update(next);}}
  function render(){
    if(run!==generation)return;state.document=doc();const skins=doc().skins??defaultSkins();if(previewSkin&&!skins.entries.some(s=>s.id===previewSkin))previewSkin=0;const skin=skins.entries.find(s=>s.id===previewSkin);const skinOptions=`<option value="0" ${previewSkin===0?"selected":""}>Original / save-file skin</option>`+skins.entries.map(s=>`<option value="${s.id}" ${previewSkin===s.id?"selected":""}>${esc(s.name)}</option>`).join("");const b=doc().buttons.find(b=>b.id===selected),status=getCGearQuickActionsStatus({...project,originalRomBytes:baseBytes}),result=compile(doc(),assets),diagnostics=result.diagnostics,errors=diagnostics.filter(d=>d.severity==="error");
    if(result.archive){lastArchive=result.archive;lastNativeGraphics=result.nativeGraphics;lastIndices=new Map(doc().buttons.map((b,i)=>[b.id,i]));}
    const options=actions.map(a=>{const mismatch=a.item&&(assets.itemGroups.get(a.item)!==a.group||(a.alternate&&assets.itemGroups.get(a.alternate)!==(a.id==="splicers"?29:a.group)));const name=a.item?assets.itemNames.get(a.item):undefined;return `<option value="${a.id}" ${b?.action===a.id?"selected":""} ${mismatch?"disabled":""}>${esc(a.name)}${name&&name!==a.name?` · ${esc(name)}`:""}${mismatch?" — incompatible handler":""}</option>`;}).join("");
    root.innerHTML=`<section class="cgear-editor"><header class="cgear-editor__header"><div><h1>C-Gear Buttons</h1><p>Design up to eight native touch shortcuts. Players can rearrange them with the wrench.</p></div><span class="cgear-status ${errors.length?"-error":hasUnappliedButtons(project)?"-pending":""}">${hasUnappliedButtons(project)?"Unapplied changes":state.enabled?"Applied · enabled":"Disabled"}</span></header>
      <div class="cgear-toolbar"><button class="btn" data-op="undo" ${history.canUndo?"":"disabled"}>Undo</button><button class="btn" data-op="redo" ${history.canRedo?"":"disabled"}>Redo</button><label><input type="checkbox" id="cg-snap" ${snap?"checked":""}> 8 px snap</label><label>Zoom <select id="cg-zoom">${[1,2,3,4].map(z=>`<option ${zoom===z?"selected":""}>${z}</option>`).join("")}</select></label><button class="btn -primary" data-op="apply" ${busy||errors.length||!status.compatible?"disabled":""}>${status.installed?(status.updateAvailable?"Update / Apply Changes":state.enabled?"Apply Changes":"Enable in ROM"):"Install / Enable"}</button><button class="btn" data-op="disable" ${busy||!status.enabled||!status.compatible?"disabled":""}>Disable</button><button class="btn cgear-delete" data-op="remove" ${busy||!status.canRemove?"disabled":""}>× Remove staged patch</button></div>
      <p class="cgear-message" aria-live="polite">${esc(message||status.message)}</p><div class="cgear-columns">
      <aside class="cgear-card"><h2>Buttons <span>${doc().buttons.length} / 8</span></h2><div class="cgear-list">${doc().buttons.map((c,i)=>`<button class="cgear-list-item ${c.id===selected?"-selected":""}" data-select="${c.id}" title="Center ${c.x}, ${c.y} · layer ${i+1}" style="--button-color:${/^#[0-9a-f]{6}$/i.test(c.color)?c.color:"#ffffff"}"><span>${esc(c.label||"Untitled")}</span><small>${esc(actionFor(c.action)?.name??"Unknown action")}</small></button>`).join("")||"<p>No buttons. Add one to begin.</p>"}</div><button class="btn cgear-add" data-op="add" ${doc().buttons.length===8?"disabled":""}>+ Add Button</button><button class="btn cgear-delete" data-op="delete" ${b?"":"disabled"}>× Delete</button><label class="cgear-native-toggle"><input id="cg-hide-communication" type="checkbox" ${doc().hideCommunicationButtons?"checked":""}> Hide communication buttons</label><section class="cgear-skins"><h2>Skins <span>${skins.entries.length} / ${MAX_SKINS}</span></h2><label>Preview skin<select id="cg-skin">${skinOptions}</select></label><button class="btn" data-op="next-skin">Next skin →</button><label>Starting skin<select id="cg-skin-default"><option value="0" ${skins.defaultId===0?"selected":""}>Original / save-file skin</option>${skins.entries.map(s=>`<option value="${s.id}" ${skins.defaultId===s.id?"selected":""}>${esc(s.name)}</option>`).join("")}</select></label>${skin?`<label>Skin name<input id="cg-skin-name" maxlength="80" value="${esc(skin.name)}"></label><div class="cgear-layer"><button class="btn" data-op="skin-earlier" ${skins.entries[0]?.id===previewSkin?"disabled":""}>Earlier</button><button class="btn" data-op="skin-later" ${skins.entries.at(-1)?.id===previewSkin?"disabled":""}>Later</button></div><button class="btn cgear-delete" data-op="delete-skin">× Remove skin</button>`:""}<button class="btn cgear-add" data-op="import-skin" ${skins.entries.length>=MAX_SKINS?"disabled":""}>+ Import .cgb skins</button><input id="cg-skin-file" type="file" accept=".cgb" multiple hidden><p class="cgear-help">15 BW2 skins are bundled. Import native BW2 .cgb files; their palettes are preserved. Tap the upper-right circle in game to cycle in this order.</p></section></aside>
      <main class="cgear-preview"><div class="cgear-preview-controls"><label><input id="cg-power" type="checkbox" ${power?"checked":""}> Wireless on</label><label>Theme <select id="cg-theme">${["Theme 1","Theme 2","Theme 3","Theme 4","Theme 5","Theme 6"].map((n,i)=>`<option value="${i}" ${theme===i?"selected":""}>${n}</option>`).join("")}</select></label><label>Pattern <select id="cg-design">${[0,1,2,3,4].map(i=>`<option value="${i}" ${design===i?"selected":""}>${i+1}</option>`).join("")}</select></label><label>Pattern set <select id="cg-gender"><option value="0" ${gender===0?"selected":""}>Male</option><option value="1" ${gender===1?"selected":""}>Female</option></select></label><label>Appearance <select id="cg-pose">${["Normal","Active","Pressed","Unavailable"].map((n,i)=>`<option value="${i}" ${pose===i?"selected":""}>${n}</option>`).join("")}</select></label></div><canvas id="cg-canvas" width="256" height="192" tabindex="0" aria-label="Drag buttons on the C-Gear preview. Arrow keys move the selected button." style="width:${256*zoom}px;height:${192*zoom}px"></canvas><p><strong>${esc(skin?.name??"Original ROM background")}</strong>${skin?"":" · In game, an existing save-file skin is retained."}</p></main>
      <aside class="cgear-card"><h2>${b?"Selected button":"Button properties"}</h2>${b?`<label>Label<input id="cg-label" maxlength="32" value="${esc(b.label)}" spellcheck="false"></label><p class="cgear-help">Uppercase native glyphs, up to 28 foreground pixels.</p><label>Outline color<input id="cg-color" type="color" value="${/^#[0-9a-f]{6}$/i.test(b.color)?b.color:"#c068f0"}"></label><div class="cgear-swatches">${colors.map(c=>`<button style="background:${c}" data-color="${c}" aria-label="Outline ${c}" title="${c}"></button>`).join("")}</div><p class="cgear-help">Black lettering and the outer black border are fixed. Colors are converted to DS precision.</p><label>Action<select id="cg-action">${options}</select></label><p class="cgear-help">${actionFor(b.action)?.item?"Hidden without the required key item; native use restrictions apply.":b.action==="repel"?"Unlimited native Repel, with no item consumption.":b.action==="bag"?"Opens the native bag, including normal item use and party handoffs.":b.action==="party"?"Opens the native party menu; unavailable when the party is empty.":"Native PC script 10090."}</p><p class="cgear-help">Only usable field key items are listed. Story and passive items have no usable field action.</p><div class="cgear-coordinates"><label>Center X<input id="cg-x" type="number" min="16" max="240" value="${b.x}"></label><label>Center Y<input id="cg-y" type="number" min="16" max="176" value="${b.y}"></label></div><label>Save-flag visibility<select id="cg-flag-mode"><option value="none" ${!b.flag?"selected":""}>No additional flag</option><option value="set" ${b.flag?.when==="set"?"selected":""}>Show when flag is set</option><option value="clear" ${b.flag?.when==="clear"?"selected":""}>Hide when flag is set</option></select></label>${b.flag?`<label>Saved flag<input id="cg-flag" value="0x${b.flag.id.toString(16).toUpperCase().padStart(4,"0")}" spellcheck="false"></label><p class="cgear-help">1–3059; decimal or hexadecimal. The installer only reads this flag.</p>`:""}`:"<p>Select a button, or use + Add Button.</p>"}<h3>Diagnostics</h3><div class="cgear-diagnostics">${diagnostics.filter(d=>!b||!d.button||d.button===b.id).map(d=>`<p class="-${d.severity}">${esc(d.message)}</p>`).join("")||"<p>Ready to compile.</p>"}</div>${result.budget?`<p class="cgear-help">Sprite memory: ${result.budget.bytes.toLocaleString()} / ${result.budget.capacity.toLocaleString()} bytes. OAM: ${result.budget.oam} / 128. Eight palettes: 256 bytes.</p>`:""}</aside></div></section>`;
    const flushInput=()=>{const active=document.activeElement;if(active instanceof HTMLInputElement&&root.contains(active))active.blur();};
    // Keep a click from being lost when an input commit replaces the form.
    root.querySelectorAll<HTMLButtonElement>("button").forEach(el=>el.onpointerdown=e=>e.preventDefault());
    const canvas=root.querySelector<HTMLCanvasElement>("#cg-canvas")!;draw(canvas,lastArchive);
    root.querySelectorAll<HTMLElement>("[data-select]").forEach(el=>el.onclick=()=>{flushInput();selected=Number(el.dataset.select);render();});
    root.querySelectorAll<HTMLElement>("[data-color]").forEach(el=>el.onclick=()=>{flushInput();edit(b=>b.color=el.dataset.color!);});
    root.querySelectorAll<HTMLButtonElement>("[data-op]").forEach(el=>el.onclick=()=>{flushInput();void operate(el.dataset.op!);});
    function changed<T extends HTMLInputElement|HTMLSelectElement>(id:string,fn:(el:T)=>void){const el=root.querySelector<T>(`#${id}`);if(el){el.onchange=()=>fn(el);if(el instanceof HTMLInputElement)el.onblur=()=>fn(el);}}
    changed<HTMLInputElement>("cg-hide-communication",el=>{const next=structuredClone(doc());next.hideCommunicationButtons=el.checked;update(next);});
    changed<HTMLInputElement>("cg-power",el=>{power=el.checked;render();});changed<HTMLInputElement>("cg-snap",el=>{snap=el.checked;});changed<HTMLSelectElement>("cg-zoom",el=>{zoom=Number(el.value);render();});
    for(const id of ["theme","design","gender","pose"])changed<HTMLSelectElement>(`cg-${id}`,el=>{const v=Number(el.value);if(id==="theme")theme=v;else if(id==="design")design=v;else if(id==="gender")gender=v;else pose=v;render();});
    changed<HTMLSelectElement>("cg-skin",el=>{previewSkin=Number(el.value);render();});
    root.querySelector<HTMLSelectElement>("#cg-skin-default")!.title="Starting skin for saves without a stored carousel choice. A player's saved choice takes priority.";
    changed<HTMLSelectElement>("cg-skin-default",el=>{const next=structuredClone(doc());next.skins!.defaultId=Number(el.value);update(next);});
    changed<HTMLInputElement>("cg-skin-name",el=>{const next=structuredClone(doc()),skin=next.skins!.entries.find(s=>s.id===previewSkin);if(skin){skin.name=el.value;update(next);}});
    root.querySelector<HTMLInputElement>("#cg-skin-file")!.onchange=async e=>{
      const input=e.target as HTMLInputElement,files=Array.from(input.files??[]);if(!files.length)return;
      try{const additions=await Promise.all(files.map(async file=>{if(!/\.cgb$/i.test(file.name))throw new Error("Import BW2 .cgb skin files.");return {name:file.name.replace(/\.cgb$/i,""),data:encodeSkin(new Uint8Array(await file.arrayBuffer()))};}));if(run!==generation)return;
        const next=structuredClone(doc()),skins=next.skins!;if(skins.entries.length+additions.length>MAX_SKINS)throw new Error("A carousel supports up to 64 skins.");
        for(const a of additions){if(skins.entries.some(s=>s.data===a.data))throw new Error(`${a.name} is already in the carousel.`);if(skins.nextId>4095)throw new Error("Skin IDs are exhausted.");const skin={...a,name:a.name.slice(0,80)||"Imported skin",id:skins.nextId++};skins.entries.push(skin);previewSkin=skin.id;}
        message=`Imported ${additions.length} skin${additions.length===1?"":"s"}. Apply Changes to include them in your ROM.`;update(next);
      }catch(e){message=(e as Error).message;render();}
    };
    changed<HTMLInputElement>("cg-label",el=>edit(b=>b.label=el.value.toUpperCase()));changed<HTMLInputElement>("cg-color",el=>edit(b=>b.color=el.value));
    changed<HTMLSelectElement>("cg-action",el=>edit(b=>b.action=el.value as Button["action"]));
    for(const id of ["x","y"]as const)changed<HTMLInputElement>(`cg-${id}`,el=>edit(b=>b[id]=Math.round(Number(el.value))));
    changed<HTMLSelectElement>("cg-flag-mode",el=>edit(b=>b.flag=el.value==="none"?undefined:{id:b.flag?.id??1517,when:el.value as "set"|"clear"}));changed<HTMLInputElement>("cg-flag",el=>edit(b=>{if(b.flag)b.flag.id=Number.isFinite(Number(el.value.trim()))?Number(el.value.trim()):0;}));
    let drag:{before:Document;x:number;y:number;bx:number;by:number;id:number}|undefined;
    const point=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*256/r.width,y:(e.clientY-r.top)*192/r.height};};
    canvas.title="Tap the upper-right circle to preview the next skin. Drag custom buttons to position them.";
    canvas.onpointerdown=e=>{const p=point(e);if((p.x-208)**2+(p.y-18)**2<=256){void operate("next-skin");return;}const hit=[...doc().buttons].reverse().find(c=>(c.x-p.x)**2+(c.y-p.y)**2<=256);if(!hit)return;selected=hit.id;drag={before:structuredClone(doc()),x:p.x,y:p.y,bx:hit.x,by:hit.y,id:hit.id};canvas.setPointerCapture(e.pointerId);canvas.focus();draw(canvas,lastArchive);};
    canvas.onpointermove=e=>{if(!drag)return;const p=point(e),c=doc().buttons.find(b=>b.id===drag!.id)!;const step=snap?8:1;c.x=Math.max(16,Math.min(240,Math.round((drag.bx+p.x-drag.x)/step)*step));c.y=Math.max(16,Math.min(176,Math.round((drag.by+p.y-drag.y)/step)*step));const r=compile(doc(),assets);if(r.archive){lastArchive=r.archive;lastNativeGraphics=r.nativeGraphics;lastIndices=new Map(doc().buttons.map((b,i)=>[b.id,i]));}draw(canvas,lastArchive);};
    canvas.onpointerup=()=>{if(!drag)return;const before=drag.before;drag=undefined;update(structuredClone(doc()),before);root.querySelector<HTMLCanvasElement>("canvas")?.focus();};
    canvas.onpointercancel=()=>{if(drag){history.document=drag.before;state.document=doc();drag=undefined;render();}};
    canvas.onkeydown=e=>{if(e.key.startsWith("Arrow")){e.preventDefault();const n=e.shiftKey?8:1;edit(b=>{b.x=Math.max(16,Math.min(240,b.x+(e.key==="ArrowRight"?n:e.key==="ArrowLeft"?-n:0)));b.y=Math.max(16,Math.min(176,b.y+(e.key==="ArrowDown"?n:e.key==="ArrowUp"?-n:0)));});root.querySelector<HTMLCanvasElement>("canvas")?.focus();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();void operate(e.shiftKey?"redo":"undo");}};
  }
  async function operate(op:string){
    if(op==="undo"||op==="redo"){history[op]();if(!doc().buttons.some(b=>b.id===selected))selected=doc().buttons[0]?.id;state.document=doc();onDirty();render();return;}
    if(["apply","disable","remove"].includes(op)){busy=true;render();try{project.originalRomBytes=(await resolveButtonAssets(project)).bytes;if(op==="apply")await installCGearQuickActions(project);else if(op==="disable")disableCGearQuickActions(project);else removeCGearQuickActions(project);Object.assign(state,project.cgearButtons);project.cgearButtons=state;history.document=state.document;message=op==="apply"?"Buttons and skins compiled and applied. Export your ROM to use them.":op==="disable"?"Buttons disabled; the design and saved preferences are retained.":"Staged patch removed; the editable design is retained.";onDirty();}catch(e){message=(e as Error).message;}finally{busy=false;render();}return;}
    if(op==="import-skin"){root.querySelector<HTMLInputElement>("#cg-skin-file")!.click();return;}
    if(op==="next-skin"){const ids=[0,...doc().skins!.entries.map(s=>s.id)];previewSkin=ids[(ids.indexOf(previewSkin)+1)%ids.length];render();return;}
    if(["delete-skin","skin-earlier","skin-later"].includes(op)){
      const next=structuredClone(doc()),skins=next.skins!,i=skins.entries.findIndex(s=>s.id===previewSkin);if(i<0)return;
      if(op==="delete-skin"){skins.entries.splice(i,1);if(skins.defaultId===previewSkin)skins.defaultId=0;previewSkin=0;}
      else{const j=i+(op==="skin-earlier"?-1:1);if(j>=0&&j<skins.entries.length)[skins.entries[i],skins.entries[j]]=[skins.entries[j],skins.entries[i]];}
      update(next);return;
    }
    const next=structuredClone(doc()),i=next.buttons.findIndex(b=>b.id===selected);
    if(op==="add"&&next.buttons.length<8){const b=newButton(next);next.buttons.push(b);selected=b.id;}
    else if(op==="delete"&&i>=0){next.buttons.splice(i,1);selected=next.buttons[Math.min(i,next.buttons.length-1)]?.id;}
    update(next);
  }
  function draw(canvas:HTMLCanvasElement,archive?:Uint8Array){const ctx=canvas.getContext("2d")!;ctx.imageSmoothingEnabled=false;
    const skin=doc().skins?.entries.find(s=>s.id===previewSkin);
    try{const bytes=skin?skinBytes(skin.data):undefined,key=`${theme}:${gender}:${design}:${power}:${!!doc().hideCommunicationButtons}:${bytes?fingerprint(bytes):0}`;let background=backgroundCache.get(key);if(!background){background=nativePreview(assets.native,theme,gender,design,power,bytes,!!doc().hideCommunicationButtons,lastNativeGraphics);backgroundCache.set(key,background);if(backgroundCache.size>8)backgroundCache.delete(backgroundCache.keys().next().value!);}ctx.putImageData(new ImageData(background.pixels as Uint8ClampedArray<ArrayBuffer>,256,192),0,0);}
    catch(e){ctx.fillStyle="#101018";ctx.fillRect(0,0,256,192);message=`Native preview: ${(e as Error).message}`;}
    if(archive)for(let i=0;i<doc().buttons.length;i++){const b=doc().buttons[i];try{if(!lastIndices.has(b.id))continue;const art=preview(archive,lastIndices.get(b.id)??-1,pose,design,theme,gender,assets.native),temp=document.createElement("canvas");temp.width=temp.height=32;temp.getContext("2d")!.putImageData(new ImageData(art.pixels as Uint8ClampedArray<ArrayBuffer>,32,32),0,0);ctx.drawImage(temp,b.x-16,b.y-16);}catch{/* Invalid draft keeps diagnostics rather than discarding edits. */}}
    const b=doc().buttons.find(b=>b.id===selected);if(b){ctx.strokeStyle="#ffffff";ctx.setLineDash([2,2]);ctx.strokeRect(b.x-16+.5,b.y-16+.5,31,31);ctx.setLineDash([]);}
  }
  render();
}
