"""Generate native Learnset companions from Ruby without updating shipped assets."""
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
ORIGINAL = REPO / "runtime/learnset-viewer"
BUILD = HERE / "build"
GENERATED = BUILD / "generated"
COMPILER = HERE.parent / "native_compiler.rb"


def input_files():
    shared = ["build.py", "layout.h", "info.h", "background.py", "generated.py", "info_messages.json"]
    return sorted(HERE.glob("*.rb")) + sorted((HERE / "abi").glob("*.h")) + [
        COMPILER, HERE.parent / "compiler.rb", Path(__file__),
        *(ORIGINAL / name for name in shared),
    ]


def input_hashes():
    return {os.path.relpath(file, REPO): hashlib.sha256(file.read_bytes()).hexdigest() for file in input_files()}


def run(*args, **kwargs):
    subprocess.run([str(arg) for arg in args], check=True, **kwargs)


def generate():
    GENERATED.mkdir(parents=True, exist_ok=True)
    shutil.copytree(HERE / "abi", GENERATED / "abi", dirs_exist_ok=True)
    shutil.copyfile(ORIGINAL / "layout.h", GENERATED / "abi/layout.h")
    shutil.copyfile(ORIGINAL / "info.h", GENERATED / "info.h")
    # These are ABI declarations only; hook prologues remain generated by the
    # original ROM-pinned builder. No original implementation is compiled.
    with (GENERATED / "abi/menu_records.h").open("a") as stream:
        stream.write('\nextern "C" void OriginalMenuCreate(void*,void*,u32*);\n'
                     'extern "C" void OriginalMenuSelect(void*);\n'
                     'extern "C" u32 OriginalDispatch(void*,int*,void*);\n')
    includes = {
        "logic": ["abi/bridge.h", "abi/logic.h"],
        "info_logic": ["abi/bridge.h", "abi/info_logic.h"],
        "runtime": ["abi/bridge.h", "abi/runtime.h"],
        "menu": ["runtime.h", "abi/menu_records.h"],
        "viewer": ["runtime.h", "info.h", "abi/viewer_records.h"],
        "info": ["runtime.h", "info.h", "info_logic.generated.h", "info_messages.generated.h",
                 "info_background.generated.h", "abi/info_records.h"],
        "memory": ["abi/bridge.h"], "config": ["runtime.h"],
    }
    for stem, headers in includes.items():
        filename = {"logic": "logic.generated.h", "info_logic": "info_logic.generated.h", "runtime": "runtime.h"}.get(stem, stem + ".cpp")
        output = GENERATED / filename
        args = [os.environ.get("RUBY", "ruby"), COMPILER, "--source", HERE / (stem + ".rb"), "--output", output]
        for header in headers:
            args += ["--include", header]
        run(*args)
        if output.suffix == ".h":
            output.write_text("#pragma once\n" + output.read_text())


def main():
    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / "verification.json").unlink(missing_ok=True)
    (BUILD / "build-report.json").unlink(missing_ok=True)
    generate()
    env = dict(os.environ, LEARNSET_BUILD_DIR=str(BUILD / "native"),
               LEARNSET_ASSET_DIR=str(BUILD / "candidates"), LEARNSET_SOURCE_DIR=str(GENERATED))
    log = BUILD / "build.log"
    try:
        with log.open("w") as stream:
            run(sys.executable, ORIGINAL / "build.py", env=env, stdout=stream, stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError:
        print("\n".join(log.read_text().splitlines()[-60:]), file=sys.stderr)
        raise
    outputs = {}
    for file in sorted((BUILD / "candidates").glob("*.dll")):
        outputs[file.name] = {"bytes": file.stat().st_size, "sha256": hashlib.sha256(file.read_bytes()).hexdigest()}
        print(f"{file.name}: {file.stat().st_size} bytes")
    native = {file.name: hashlib.sha256(file.read_bytes()).hexdigest()
              for file in sorted((BUILD / "native").glob("Learnset*.elf"))
              if file.name in [f"Learnset{group}{game}.elf" for group in ("Menu", "Viewer") for game in ("W2", "B2")]}
    (BUILD / "build-report.json").write_text(json.dumps({"inputs": input_hashes(), "outputs": outputs, "native": native, "published": False}, indent=2) + "\n")


if __name__ == "__main__":
    main()
