#ifndef __W2U_ITEMS_H
#define __W2U_ITEMS_H

#include "swan/swantypes.h"

typedef u32 ITEM;

#define ITEM_NULL 0
#define ITEM_MASTER_BALL 1
#define ITEM_CHERI_BERRY 149
#define ITEM_SITRUS_BERRY 158
#define ITEM_OCCA_BERRY 184
#define ITEM_PASSHO_BERRY 185
#define ITEM_WACAN_BERRY 186
#define ITEM_RINDO_BERRY 187
#define ITEM_YACHE_BERRY 188
#define ITEM_CHOPLE_BERRY 189
#define ITEM_KEBIA_BERRY 190
#define ITEM_SHUCA_BERRY 191
#define ITEM_COBA_BERRY 192
#define ITEM_LIGHT_CLAY 269
#define ITEM_PAYAPA_BERRY 193
#define ITEM_TANGA_BERRY 194
#define ITEM_CHARTI_BERRY 195
#define ITEM_KASIB_BERRY 196
#define ITEM_HABAN_BERRY 197
#define ITEM_COLBUR_BERRY 198
#define ITEM_BABIRI_BERRY 199
#define ITEM_CHILAN_BERRY 200
#define ITEM_LEFTOVERS 234

#define ITEM_MEGITE 113
#define ITEM_PROTECTIVE_PADS 114
#define ITEM_TERRAIN_EXTENDER 115
#define ITEM_ABILITY_CAPSULE 120
#define ITEM_ASSAULT_VEST 121
#define ITEM_LUMINOUS_MOSS 122
#define ITEM_MARANGA_BERRY 123
#define ITEM_MEGA_RING 124
#define ITEM_FAIRY_FEATHER 125
#define ITEM_ROSELI_BERRY 126
#define ITEM_SAFETY_GOGGLES 127
#define ITEM_SNOWBALL 128
#define ITEM_WEAKNESS_POLICY 129
#define ITEM_ABILITY_PATCH 130

#define ITEM_ELECTRIC_SEED 485
#define ITEM_GRASSY_SEED 486
#define ITEM_PSYCHIC_SEED 487
#define ITEM_MISTY_SEED 488

#define ITEM_VENUSAURITE 505
#define ITEM_CHARIZARDITE_X 506
#define ITEM_CHARIZARDITE_Y 507
#define ITEM_BLASTOISINITE 508
#define ITEM_BEEDRILLITE 509
#define ITEM_PIDGEOTITE 510
#define ITEM_ALAKAZITE 511
#define ITEM_SLOWBRONITE 512
#define ITEM_GENGARITE 513
#define ITEM_KANGASKHANITE 514
#define ITEM_PINSIRITE 515
#define ITEM_GYARADOSITE 516
#define ITEM_AERODACTYLITE 517
#define ITEM_MEWTWONITE_X 518
#define ITEM_MEWTWONITE_Y 519
#define ITEM_AMPHAROSITE 520
#define ITEM_STEELIXITE 521
#define ITEM_SCIZORITE 522
#define ITEM_HERACRONITE 523
#define ITEM_HOUNDOOMINITE 524
#define ITEM_TYRANITARITE 525
#define ITEM_SCEPTILITE 526
#define ITEM_BLAZIKENITE 527
#define ITEM_SWAMPERTITE 528
#define ITEM_GARDEVOIRITE 529
#define ITEM_SABLENITE 530
#define ITEM_MAWILITE 531
#define ITEM_AGGRONITE 592
#define ITEM_MEDICHAMITE 593
#define ITEM_MANECTITE 594
#define ITEM_SHARPEDONITE 595
#define ITEM_CAMERUPTITE 596
#define ITEM_ALTARIANITE 597
#define ITEM_BANETTITE 598
#define ITEM_ABSOLITE 599
#define ITEM_GLALITITE 600
#define ITEM_SALAMENCITE 601
#define ITEM_METAGROSSITE 602
#define ITEM_LATIASITE 603
#define ITEM_LATIOSITE 604
#define ITEM_LOPUNNITE 605
#define ITEM_GARCHOMPITE 606
#define ITEM_LUCARIONITE 607
#define ITEM_ABOMASITE 608
#define ITEM_GALLADITE 609
#define ITEM_AUDINITE 610
#endif
