import { copyFile, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { analyzeMoveAnimationScript } from "../src/pokeweb/moveAnimationDiagnostics";
import { SPA_FIELD_REFERENCE_DOCS } from "../src/pokeweb/moveAnimationDocumentation";
import { decompileMoveAnimationBytes } from "../src/pokeweb/moveAnimationModel";
import { getMoveAnimationVmSchema } from "../src/pokeweb/moveAnimationVmSchema";
import { parseSpaArchive } from "../src/pokeweb/nitroSpa";
import { pathKind, resolveMoveAnimationWorkflowConfig } from "./lib/move-animation-workflow-config";
import { sha256 } from "./lib/move-animation-tooling";

const ROOT = path.resolve(import.meta.dirname, "..");
const WORKSPACE = path.resolve(ROOT, "..");
const GENERATED_MARKER = "<!-- Generated by npm run moveanim:docs. Do not hand-edit. -->";

type MoveOwnership = {
  moveId: number;
  moveName: string;
  file: string;
  bytes: number;
  sha256: string;
  spas: number[];
  backgrounds: number[];
  calledAnimations: number[];
  error?: string;
};

type SpaOwnership = {
  spaId: number;
  file: string;
  bytes: number;
  sha256: string;
  resources: number;
  textures: number;
  usedByMoves: number[];
  error?: string;
};

type OwnershipLedger = { moves: MoveOwnership[]; spas: SpaOwnership[] };

await generatePermanentReferences();
if (process.argv.includes("--consolidate-w2u")) await consolidateW2uReadmes();

async function generatePermanentReferences(): Promise<void> {
  const docsDir = path.join(ROOT, "docs/move-animation-editor");
  await mkdir(docsDir, { recursive: true });
  await writeFile(path.join(docsDir, "command-reference.md"), renderCommandReference());
  await writeFile(path.join(docsDir, "spa-particle-reference.md"), renderSpaReference());
  await writeFile(path.join(docsDir, "preview-swan-conformance.md"), renderConformanceReference());
  console.log("Generated move-animation command and SPA references.");
}

async function consolidateW2uReadmes(): Promise<void> {
  const config = await resolveMoveAnimationWorkflowConfig({ serverlessRoot: ROOT });
  const repositories = [
    { label: "mirror", directory: config.values.mirrorRepo },
    { label: "build", directory: config.values.buildRepo },
  ];
  let canonical: OwnershipLedger | undefined;
  for (const repository of repositories) {
    if ((await pathKind(repository.directory)) !== "directory") throw new Error(`W2U ${repository.label} repository is missing: ${repository.directory}`);
    await archiveLegacyReadmes(repository.label, repository.directory);
    const ledger = await buildOwnershipLedger(repository.directory);
    canonical ??= ledger;
    await writeFile(path.join(repository.directory, "data/graphics/move_animations/README.md"), renderMoveOwnership(ledger));
    await writeFile(path.join(repository.directory, "data/graphics/move_spas/README.md"), renderSpaOwnership(ledger));
    console.log(`Generated W2U ownership READMEs for ${repository.label}.`);
  }
  if (canonical) {
    const referenceDir = path.join(ROOT, "move-animation-reference");
    await writeFile(path.join(referenceDir, "staged-ownership.json"), `${JSON.stringify(canonical, null, 2)}\n`);
    await writeFile(path.join(referenceDir, "staged-ownership.md"), `${renderMoveOwnership(canonical)}\n${renderSpaOwnership(canonical)}`);
  }
}

async function buildOwnershipLedger(repo: string): Promise<OwnershipLedger> {
  const reference = JSON.parse(await readFile(path.join(ROOT, "move-animation-reference/move-animation-reference.json"), "utf8")) as { moves?: Array<{ moveId: number; moveName?: string; name?: string }> };
  const expansion = JSON.parse(await readFile(path.join(ROOT, "src/assets/data/white2upgradeMoveExpansion.json"), "utf8")) as { moves?: Array<{ sourceId: number; name: string }> };
  const names = new Map((reference.moves ?? []).map((move) => [move.moveId, move.moveName ?? move.name ?? `Move ${move.moveId}`]));
  for (const move of expansion.moves ?? []) names.set(move.sourceId, move.name);
  const animationDir = path.join(repo, "data/graphics/move_animations");
  const spaDir = path.join(repo, "data/graphics/move_spas");
  const moveFiles = (await readdir(animationDir)).filter((name) => /^5_\d+\.bin$/u.test(name)).sort();
  const moves: MoveOwnership[] = [];
  for (const file of moveFiles) {
    const moveId = numericFileId(file);
    const bytes = new Uint8Array(await readFile(path.join(animationDir, file)));
    try {
      const analysis = analyzeMoveAnimationScript(decompileMoveAnimationBytes(bytes));
      const calledAnimations = [...new Set(analysis.events.filter((event) => event.command === "CallMoveAnimation").map((event) => event.params[0] ?? -1).filter((id) => id >= 0))].sort(numberSort);
      moves.push({
        moveId,
        moveName: names.get(moveId) ?? `Move ${moveId}`,
        file,
        bytes: bytes.length,
        sha256: sha256(bytes),
        spas: analysis.loadedSpaIds,
        backgrounds: [...new Set(analysis.backgrounds.filter((event) => event.command === "LoadBackground" && event.backgroundId !== undefined).map((event) => event.backgroundId!))].sort(numberSort),
        calledAnimations,
      });
    } catch (error) {
      moves.push({ moveId, moveName: names.get(moveId) ?? `Move ${moveId}`, file, bytes: bytes.length, sha256: sha256(bytes), spas: [], backgrounds: [], calledAnimations: [], error: error instanceof Error ? error.message : String(error) });
    }
  }
  const spaFiles = (await readdir(spaDir)).filter((name) => /^6_\d+\.bin$/u.test(name)).sort();
  const spas: SpaOwnership[] = [];
  for (const file of spaFiles) {
    const spaId = numericFileId(file);
    const bytes = new Uint8Array(await readFile(path.join(spaDir, file)));
    const usedByMoves = moves.filter((move) => move.spas.includes(spaId)).map((move) => move.moveId);
    try {
      const archive = parseSpaArchive(bytes);
      spas.push({ spaId, file, bytes: bytes.length, sha256: sha256(bytes), resources: archive.resourceCount, textures: archive.textureCount, usedByMoves });
    } catch (error) {
      spas.push({ spaId, file, bytes: bytes.length, sha256: sha256(bytes), resources: 0, textures: 0, usedByMoves, error: error instanceof Error ? error.message : String(error) });
    }
  }
  return { moves: moves.sort((left, right) => left.moveId - right.moveId), spas: spas.sort((left, right) => left.spaId - right.spaId) };
}

async function archiveLegacyReadmes(label: string, repo: string): Promise<void> {
  const archive = path.join(WORKSPACE, "work/archive/legacy-documentation");
  await mkdir(archive, { recursive: true });
  for (const [source, target] of [
    [path.join(repo, "data/graphics/move_animations/README.md"), path.join(archive, `move-animations-${label}.md`)],
    [path.join(repo, "data/graphics/move_spas/README.md"), path.join(archive, `move-spas-${label}.md`)],
  ] as const) {
    if ((await pathKind(source)) !== "file" || (await pathKind(target)) === "file") continue;
    const text = await readFile(source, "utf8");
    if (!text.includes(GENERATED_MARKER)) await copyFile(source, target);
  }
  const archiveReadme = path.join(WORKSPACE, "work/archive/README.md");
  if ((await pathKind(archiveReadme)) !== "file") {
    await writeFile(archiveReadme, "# Archived move-animation work\n\nIgnore this directory during ordinary donor search, lint, indexing, and agent context collection. Consult an archived workspace only for that move or to extract a demonstrated general technique.\n");
  }
}

function renderCommandReference(): string {
  const commands = getMoveAnimationVmSchema();
  const lines = [GENERATED_MARKER, "", "# Move Animation VM Command Reference", "", "Generated from `src/pokeweb/moveAnimationVmSchema.ts`, command docs, and semantic aliases. Swan source locations are repository-relative.", ""];
  for (const command of commands) {
    lines.push(`## ${command.displayName} (${command.opcode})`, "", command.description, "", `- Canonical VM name: \`${command.name}\``, `- Category: ${command.category}`, `- Swan: \`${command.swan.handler}\` in \`${command.swan.source}\``, `- Preview: ${command.preview}`, `- Completion: ${command.completion}${command.taskGroup === undefined ? "" : `, task group ${command.taskGroup}`}`, `- State: reads ${command.state.reads.join(", ") || "none"}; writes ${command.state.writes.join(", ") || "none"}`, `- Accepted names: ${command.aliases.map((alias) => `\`${alias}\``).join(", ")}`, "");
    if (!command.params.length) {
      lines.push("Parameters: none.", "");
      continue;
    }
    lines.push("| # | Name | Type | Meaning |", "|---:|---|---|---|");
    for (const param of command.params) {
      const kind = param.kind === "enum" ? `enum ${param.enumGroup ?? ""}` : param.kind === "fx32" ? `FX32 ${param.fx32Unit ?? ""}` : param.signedness;
      const values = param.enumValues?.length ? ` Values: ${param.enumValues.map((value) => `\`${value.name}\`=${value.value}`).join(", ")}.` : "";
      lines.push(`| ${param.index} | \`${escapeTable(param.name)}\` | ${escapeTable(kind)} | ${escapeTable(param.description + values)} |`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderSpaReference(): string {
  const lines = [GENERATED_MARKER, "", "# SPA Particle Field Reference", "", "Generated from `SPA_FIELD_REFERENCE_DOCS` in `src/pokeweb/moveAnimationDocumentation.ts`. Clone operations should use the explicit policies in `src/pokeweb/spaTransform.ts`.", ""];
  for (const field of SPA_FIELD_REFERENCE_DOCS) {
    lines.push(`## ${field.title}`, "", `- Field: \`${field.key}\``, `- Group: ${field.group}`, `- Meaning: ${field.description}`, `- Boundary: ${field.scriptBoundary}`, `- Donor checks: ${field.donorNotes.join(" ")}`, `- Examples: ${field.vanillaExamples.join(" ")}`, "");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderConformanceReference(): string {
  const lines = [GENERATED_MARKER, "", "# Preview and Swan Conformance Matrix", "", "This table ties every VM opcode to the Swan dispatch handler and Pokeweb preview support. `supported` means the browser models visible/state behavior, `marker` means timing or intent is represented without full visuals, and `unsupported` is surfaced explicitly.", "", "| Opcode | Command | Swan handler | Preview | State | Completion |", "|---:|---|---|---|---|---|"];
  for (const command of getMoveAnimationVmSchema()) {
    lines.push(`| ${command.opcode} | \`${command.displayName}\` | \`${command.swan.handler}\` | ${command.preview} | ${command.state.reads.join(", ")} -> ${command.state.writes.join(", ")} | ${command.completion}${command.taskGroup === undefined ? "" : ` / task ${command.taskGroup}`} |`);
  }
  lines.push("", "## Fixture Coverage", "", "- Schema/alias modes: `src/test/moveAnimationToolingP1P2.test.ts` round-trips every declared enum value and checks all 78 dispatch entries.", "- Camera and projection: `src/test/moveAnimationPreviewModel.test.ts` covers presets, side swapping, relative coordinates, angles, projection, waits, and restoration.", "- Shadow Ball regression: `src/test/moveAnimationToolingP1P2.test.ts` fixes its opening `AdjustCamera INTERPOLATION_RELATIVE, 3px, 0, 3px, ...` to the Swan-relative pose.", "- Particles: `src/test/moveAnimationPreviewModel.test.ts` fixtures cover anchors, projectiles, screen/ortho placement, texture orientation, child emission, behavior, and deterministic ordering.", "- Sprite and cleanup: `src/test/gen5BattleSpriteSimulator.test.ts` plus workflow lint fixtures cover affine, palette, opacity, visibility, shadow, freeze, task waits, and terminal restoration.", "");
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderMoveOwnership(ledger: OwnershipLedger): string {
  const lines = [GENERATED_MARKER, "", "# Move Animation Overrides", "", "These files override B2W2 `a/0/6/5`. While a move is active, edit its generator under `work/<slug>/`; after finalization, the staged binary listed here is authoritative. Do not hand-edit generated binaries.", "", "| Move | Name | SPA dependencies | Backgrounds | Calls | Bytes | SHA-256 |", "|---:|---|---|---|---|---:|---|"];
  for (const move of ledger.moves) lines.push(`| ${move.moveId} | ${escapeTable(move.moveName)} | ${move.spas.join(", ") || "none"} | ${move.backgrounds.join(", ") || "none"} | ${move.calledAnimations.join(", ") || "none"} | ${move.bytes} | \`${move.sha256}\`${move.error ? ` (${escapeTable(move.error)})` : ""} |`);
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderSpaOwnership(ledger: OwnershipLedger): string {
  const lines = [GENERATED_MARKER, "", "# Move SPA Overrides", "", "These files override B2W2 `a/0/0/6`. IDs come from each `6_XXXXXXXX.bin` filename. Resource and texture counts are parsed from the staged binary.", "", "| SPA | Resources | Textures | Used by moves | Bytes | SHA-256 |", "|---:|---:|---:|---|---:|---|"];
  for (const spa of ledger.spas) lines.push(`| ${spa.spaId} | ${spa.resources} | ${spa.textures} | ${spa.usedByMoves.join(", ") || "none"} | ${spa.bytes} | \`${spa.sha256}\`${spa.error ? ` (${escapeTable(spa.error)})` : ""} |`);
  return `${lines.join("\n").trimEnd()}\n`;
}

function numericFileId(file: string): number {
  const match = /^[56]_0*(\d+)\.bin$/u.exec(file);
  if (!match) throw new Error(`Cannot read numeric ID from ${file}.`);
  return Number.parseInt(match[1]!, 10);
}

function numberSort(left: number, right: number): number {
  return left - right;
}

function escapeTable(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}
