# frozen_string_literal: true

# A deliberately small, statically checked Ruby syntax frontend. Ripper parses
# source without executing it; the output contains no Ruby runtime or heap.
require 'ripper'
require 'json'
require 'optparse'

module RubyPatch
  class Error < StandardError; end

  class Compiler
    TYPES = { u8: 'uint8_t', u16: 'uint16_t', u32: 'uint32_t',
              ptr: 'void *', bool: '_Bool', void: 'void' }.freeze
    WIDTH = { u8: 8, u16: 16, u32: 32 }.freeze
    C_KEYWORDS = %w[auto break case char const continue default do double else
                    enum extern float for goto if inline int long register
                    restrict return short signed sizeof static struct switch
                    typedef union unsigned void volatile while].freeze

    def initialize(source, profile, game)
      @tree = Ripper.sexp(source)
      raise Error, 'invalid Ruby syntax' unless @tree
      @profile, @game = profile, game
      @native, @signatures, @definitions = {}, {}, {}
    end

    def compile
      collect_declarations
      raise Error, 'at least one function is required' if @definitions.empty?
      unless @signatures.keys.sort == @definitions.keys.sort
        raise Error, 'each function must have exactly one signature and definition'
      end
      functions = @definitions.map { |name, node| compile_function(name, node) }
      output = ['/* Generated by RubyPatch; edit the .rb source. */', '#include <stdint.h>', '']
      @native.each_value do |decl|
        args = decl[:args].map { |type| TYPES.fetch(type) }.join(', ')
        output << "extern #{TYPES.fetch(decl[:returns])} #{decl[:symbol]}(#{args.empty? ? 'void' : args});"
      end
      @signatures.each do |name, decl|
        output << "static #{TYPES.fetch(decl[:returns])} rb_fn_#{name}(#{parameters(decl)});"
      end
      output.concat(['', *functions, *compile_hooks])
      output.join("\n") + "\n"
    end

    private

    def fail_at(message, node = nil)
      token = find_token(node)
      suffix = token ? " at line #{token[2][0]}, column #{token[2][1] + 1}" : ''
      raise Error, message + suffix
    end

    def find_token(node)
      return unless node.is_a?(Array)
      return node if node[0].is_a?(Symbol) && node[0].to_s.start_with?('@')
      node.each do |child|
        found = find_token(child)
        return found if found
      end
      nil
    end

    def identifier(value, node = nil)
      unless value.is_a?(String) && value.match?(/\A[a-zA-Z_][a-zA-Z0-9_]*\z/) && !C_KEYWORDS.include?(value)
        fail_at('expected an ordinary identifier', node)
      end
      value
    end

    def literal(node)
      fail_at('expected a literal declaration value', node) unless node.is_a?(Array)
      case node[0]
      when :symbol_literal
        symbol = node[1]
        fail_at('only simple symbols are supported', node) unless symbol[0] == :symbol && symbol[1][0] == :@ident
        value = symbol[1][1]
        fail_at('only simple symbols are supported', node) unless value.match?(/\A[a-zA-Z_][a-zA-Z0-9_]*\z/)
        value.to_sym
      when :string_literal
        parts = node[1]
        unless parts[0] == :string_content && parts.drop(1).all? { |part| part[0] == :@tstring_content }
          fail_at('string interpolation is not supported', node)
        end
        parts.drop(1).map { |part| part[1] }.join
      when :array
        (node[1] || []).map { |item| literal(item) }
      when :hash, :bare_assoc_hash
        pairs = node[0] == :hash ? (node[1] ? node[1][1] : []) : node[1]
        pairs.each_with_object({}) do |pair, result|
          unless pair[0] == :assoc_new && pair[1][0] == :@label
            fail_at('declaration hashes require named keys', pair)
          end
          key = identifier(pair[1][1].delete_suffix(':'), pair).to_sym
          fail_at("duplicate key #{key}", pair) if result.key?(key)
          result[key] = literal(pair[2])
        end
      else
        fail_at('declarations accept only literal symbols, strings, arrays and hashes', node)
      end
    end

    def args_list(node)
      return [] if node.nil? || node == []
      node = node[1] if node[0] == :arg_paren
      return [] unless node
      unless node[0] == :args_add_block && node[2] == false
        fail_at('blocks and splatted arguments are not supported', node)
      end
      node[1]
    end

    def type(value, allow_void: false)
      unless TYPES.key?(value) && (allow_void || value != :void)
        raise Error, "unsupported type #{value.inspect}"
      end
      value
    end

    def collect_declarations
      @tree[1].each do |node|
        next if node[0] == :void_stmt
        if node[0] == :def
          name = identifier(node[1][1], node)
          fail_at("duplicate definition #{name}", node) if @definitions.key?(name)
          @definitions[name] = node
          next
        end
        unless node[0] == :command && %w[native signature].include?(node[1][1])
          fail_at('top level accepts only native, signature and def declarations', node)
        end
        args = args_list(node[2])
        fail_at('declaration requires a name and keyword options', node) unless args.length == 2
        name, options = args.map { |arg| literal(arg) }
        fail_at('declaration name must be a symbol', node) unless name.is_a?(Symbol)
        name = identifier(name.to_s, node)
        fail_at('declaration options must be a hash', node) unless options.is_a?(Hash)
        kind = node[1][1]
        expected = kind == 'native' ? %i[args returns symbol] : %i[args returns]
        fail_at("#{kind} requires exactly #{expected.join(', ')}", node) unless options.keys.sort == expected.sort
        fail_at("duplicate declaration #{name}", node) if @native.key?(name) || @signatures.key?(name)
        result = { returns: type(options[:returns], allow_void: true) }
        if kind == 'native'
          fail_at('native args must be an array', node) unless options[:args].is_a?(Array)
          result[:args] = options[:args].map { |value| type(value) }
          result[:symbol] = identifier(options[:symbol], node)
          fail_at('native symbol already declared', node) if @native.values.any? { |decl| decl[:symbol] == result[:symbol] }
          @native[name] = result
        else
          fail_at('signature args must be a named hash', node) unless options[:args].is_a?(Hash)
          result[:args] = options[:args].transform_keys(&:to_s).transform_values { |value| type(value) }
          @signatures[name] = result
        end
      end
    end

    def parameters(decl)
      text = decl[:args].map { |name, value| "#{TYPES.fetch(value)} rb_v_#{name}" }.join(', ')
      text.empty? ? 'void' : text
    end

    def compile_function(name, node)
      @current = @signatures.fetch(name)
      @locals = {}
      params = node[2]
      params = params[1] if params && params[0] == :paren
      unless params && params[0] == :params && params.drop(2).all?(&:nil?)
        fail_at('only positional function parameters are supported', node)
      end
      names = (params[1] || []).map { |param| identifier(param[1], param) }
      unless names == @current[:args].keys
        fail_at('parameter names/order must match the signature', node)
      end
      body = node[3]
      unless body[0] == :bodystmt && body.drop(2).all?(&:nil?)
        fail_at('rescue, else and ensure bodies are not supported', body)
      end
      text, _env, returns = statements(body[1], @current[:args].dup, 1)
      if @current[:returns] != :void && !returns
        fail_at('value functions require explicit return on every path', node)
      end
      locals = @locals.map { |local, value| "  #{TYPES.fetch(value)} rb_v_#{local};" }
      ["static #{TYPES.fetch(@current[:returns])} rb_fn_#{name}(#{parameters(@current)}) {", *locals, *text, '}'].join("\n")
    end

    def compatible?(actual, expected)
      actual == expected || (WIDTH.key?(actual) && WIDTH.key?(expected) && WIDTH[actual] <= WIDTH[expected])
    end

    def statements(nodes, env, depth)
      output, returned = [], false
      (nodes || []).each do |node|
        next if node[0] == :void_stmt
        fail_at('unreachable statement after return', node) if returned
        pad = '  ' * depth
        case node[0]
        when :assign, :opassign
          lhs = node[1]
          unless lhs[0] == :var_field && lhs[1][0] == :@ident
            fail_at('only local variable assignments are supported', lhs)
          end
          name = identifier(lhs[1][1], lhs)
          if node[0] == :opassign
            fail_at('only += and -= compound assignments are supported', node) unless %w[+= -=].include?(node[2][1])
            fail_at("uninitialized local #{name}", node) unless env.key?(name)
            rhs = [:binary, [:var_ref, lhs[1]], node[2][1][0].to_sym, node[3]]
          else
            rhs = node[2]
          end
          code, value = expression(rhs, env, allow_call: true)
          fail_at('cannot assign a void result', node) if value == :void
          expected = env[name] || @locals[name] || value
          fail_at("assignment to #{name} changes type or narrows an integer", node) unless compatible?(value, expected)
          @locals[name] = expected unless @current[:args].key?(name)
          env[name] = expected
          output << "#{pad}rb_v_#{name} = #{code};"
        when :if
          condition, value = expression(node[1], env)
          fail_at('conditions require booleans; compare integers explicitly', node[1]) unless value == :bool
          yes, yes_env, yes_return = statements(node[2], env.dup, depth + 1)
          tail = node[3]
          fail_at('only if/else is supported; nest if instead of elsif', tail) if tail && tail[0] != :else
          no, no_env, no_return = statements(tail ? tail[1] : [], env.dup, depth + 1)
          output.concat(["#{pad}if (#{condition}) {", *yes])
          output.concat(["#{pad}} else {", *no]) if tail
          output << "#{pad}}"
          if yes_return && no_return
            returned = true
          elsif yes_return
            env = no_env
          elsif no_return
            env = yes_env
          else
            env = yes_env.select { |key, item| no_env[key] == item }
          end
        when :while
          condition, value = expression(node[1], env)
          fail_at('while requires a boolean condition', node[1]) unless value == :bool
          body, _body_env, _body_return = statements(node[2], env.dup, depth + 1)
          output.concat(["#{pad}while (#{condition}) {", *body, "#{pad}}"])
        when :return0, :return
          args = node[0] == :return0 ? [] : args_list(node[1])
          if @current[:returns] == :void
            fail_at('void functions use bare return', node) unless args.empty?
            output << "#{pad}return;"
          else
            fail_at('return requires exactly one value', node) unless args.length == 1
            code, value = expression(args[0], env, allow_call: true)
            fail_at('return type mismatch or narrowing', node) unless compatible?(value, @current[:returns])
            output << "#{pad}return #{code};"
          end
          returned = true
        else
          unless node[0] == :method_add_arg
            fail_at("unsupported statement #{node[0]}", node)
          end
          code, _value = expression(node, env, allow_call: true)
          output << "#{pad}#{code};"
        end
      end
      [output, env, returned]
    end

    def expression(node, env, allow_call: false)
      fail_at('missing expression', node) unless node.is_a?(Array)
      case node[0]
      when :@int
        value = Integer(node[1].delete('_'))
        fail_at('integer literal must fit u32', node) unless value.between?(0, 0xffffffff)
        ["UINT32_C(#{value})", :u32]
      when :var_ref
        token = node[1]
        if token[0] == :@kw && %w[true false].include?(token[1])
          return [token[1] == 'true' ? '1' : '0', :bool]
        end
        fail_at('only local variables and true/false are supported', node) unless token[0] == :@ident
        name = token[1]
        fail_at("uninitialized local #{name}", node) unless env.key?(name)
        ["rb_v_#{name}", env.fetch(name)]
      when :paren
        fail_at('parentheses require one expression', node) unless node[1].length == 1
        expression(node[1][0], env, allow_call: allow_call)
      when :binary
        left, lt = expression(node[1], env)
        right, rt = expression(node[3], env)
        op = node[2].to_s
        if %w[&& ||].include?(op)
          fail_at('logical operators require two booleans', node) unless lt == :bool && rt == :bool
          ["(#{left} #{op} #{right})", :bool]
        elsif %w[== !=].include?(op) && lt == rt && %i[ptr bool].include?(lt)
          ["(#{left} #{op} #{right})", :bool]
        else
          unless WIDTH.key?(lt) && WIDTH.key?(rt) && %w[+ - * & | ^ < <= > >= == !=].include?(op)
            fail_at('unsupported operator or operand types', node)
          end
          operands = "((uint32_t)(#{left}) #{op} (uint32_t)(#{right}))"
          if %w[< <= > >= == !=].include?(op)
            [operands, :bool]
          else
            ["((uint32_t)#{operands})", :u32]
          end
        end
      when :unary
        code, value = expression(node[2], env)
        fail_at('only boolean ! is supported', node) unless node[1] == :! && value == :bool
        ["(!#{code})", :bool]
      when :method_add_arg
        fail_at('calls must be standalone, assigned or returned; nested calls are unsupported', node) unless allow_call
        call = node[1]
        fail_at('only declared plain function calls are supported', node) unless call[0] == :fcall
        name = call[1][1]
        decl = @native[name] || @signatures[name]
        fail_at("undeclared function #{name}", node) unless decl
        args = args_list(node[2])
        expected = @native.key?(name) ? decl[:args] : decl[:args].values
        fail_at("wrong argument count for #{name}", node) unless args.length == expected.length
        compiled = args.each_with_index.map do |arg, index|
          code, value = expression(arg, env)
          unless compatible?(value, expected[index])
            fail_at("argument #{index + 1} of #{name} has wrong type or narrows an integer", arg)
          end
          code
        end
        symbol = @native.key?(name) ? decl[:symbol] : "rb_fn_#{name}"
        ["#{symbol}(#{compiled.join(', ')})", decl[:returns]]
      else
        fail_at("unsupported expression #{node[0]}", node)
      end
    end

    def compile_hooks
      entry = identifier(@profile.fetch('entry'))
      decl = @signatures[entry]
      raise Error, 'hook entry must name a defined function' unless decl
      game = @profile.fetch('games').fetch(@game)
      overlay = game.fetch('overlay')
      raise Error, 'overlay must be a nonnegative integer' unless overlay.is_a?(Integer) && overlay.between?(0, 9999)
      sites = game.fetch('hooks').map { |address| Integer(address) }
      raise Error, 'hooks must be unique, aligned u32 addresses' unless !sites.empty? && sites.uniq == sites && sites.all? { |site| site.between?(0, 0xffffffff) && site.even? }
      sites.map do |site|
        name = "THUMB_BRANCH_LINK_#{overlay}_0x#{site.to_s(16).upcase}"
        args = decl[:args].keys.map { |arg| "rb_v_#{arg}" }.join(', ')
        call = "rb_fn_#{entry}(#{args});"
        call = "return #{call}" unless decl[:returns] == :void
        "\n#{TYPES.fetch(decl[:returns])} #{name}(#{parameters(decl)}) {\n  #{call}\n}"
      end
    end
  end
end

if $PROGRAM_NAME == __FILE__
  options = {}
  parser = OptionParser.new do |opts|
    opts.banner = 'Usage: ruby compiler.rb --source patch.rb --profile patch.json --game B2|W2 --output patch.c'
    %i[source profile game output].each { |key| opts.on("--#{key} VALUE") { |value| options[key] = value } }
  end
  begin
    parser.parse!
    raise RubyPatch::Error, parser.to_s unless ARGV.empty? && %i[source profile game output].all? { |key| options.key?(key) }
    raise RubyPatch::Error, 'MVP supports only B2 and W2' unless %w[B2 W2].include?(options[:game])
    compiler = RubyPatch::Compiler.new(File.read(options[:source]), JSON.parse(File.read(options[:profile])), options[:game])
    result = compiler.compile
    File.write(options[:output], result)
  rescue RubyPatch::Error, OptionParser::ParseError, JSON::ParserError, KeyError, ArgumentError, SystemCallError => error
    warn "RubyPatch: #{error.message}"
    exit 1
  end
end
